name: Compile Uebungen
on: push

jobs:
  compile:
    name: Compile documents
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/small@v1
        with:
          run: |
            sh build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: documents
          path: out/*.pdf
